"""Document generators.

Each generator pairs one output file with one prompt builder from
`prompts.py`. Adding a new generated document means adding a prompt
builder and a small subclass here, then listing it in `PIPELINE_ORDER`
and the config's `docs` list.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime, timezone

from repobrain.docgen import prompts
from repobrain.docgen.context import ProjectContext
from repobrain.llm.base import LLMProvider
from repobrain.logging_setup import get_logger

logger = get_logger("docgen")

_FOOTER = (
    "\n\n---\n*Generated by [RepoBrain](https://github.com) on {timestamp} "
    "from static analysis of the repository. Review before relying on it "
    "for anything safety-critical — it reflects code structure, not intent.*\n"
)


class DocGenerator(ABC):
    #: Output filename, e.g. "README.md". Used as the key in config `docs`
    #: and as the fingerprint key for incremental regeneration.
    filename: str

    @abstractmethod
    def build_prompt(self, ctx: ProjectContext) -> str:
        raise NotImplementedError

    def generate(self, ctx: ProjectContext, llm: LLMProvider) -> str:
        prompt = self.build_prompt(ctx)
        logger.info("Generating %s (%d char prompt)", self.filename, len(prompt))
        body = llm.generate(prompt, system=prompts.SYSTEM_PROMPT)
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        return body.rstrip() + _FOOTER.format(timestamp=timestamp)


class ReadmeGenerator(DocGenerator):
    filename = "README.md"

    def build_prompt(self, ctx: ProjectContext) -> str:
        return prompts.build_readme_prompt(ctx)


class ArchitectureGenerator(DocGenerator):
    filename = "ARCHITECTURE.md"

    def build_prompt(self, ctx: ProjectContext) -> str:
        return prompts.build_architecture_prompt(ctx)


class SequenceDiagramGenerator(DocGenerator):
    filename = "SEQUENCE.md"

    def build_prompt(self, ctx: ProjectContext) -> str:
        return prompts.build_sequence_prompt(ctx)


ALL_GENERATORS: list[DocGenerator] = [
    ReadmeGenerator(),
    ArchitectureGenerator(),
    SequenceDiagramGenerator(),
]
